### ISSUE TITLE
Progression

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-projects#14]
It has been widely observed that web3 offerings are hobbled by the user loss at the very first steps of the onboarding process: authentication and wallet formation.

It seems wise, when introducing a new application to a new user for them to onboard in the simplest, well known way to them. So, Google oauth, etc, and wallet handled centrally. But then in a period of time, the user should get emails with instructions to take control of their identity and wallet. 

Web3 ventures can do this for themselves, but what if this was something handled for them by a specialist in that onboarding and transfer procedure? What would a pluggable Progression service look like?

**Comment by brian-lc** [comment]
This seems similar to https://github.com/ConsenSys/web3studio-projects/issues/50 duplicate? Re-open if it is not
