### ISSUE TITLE
Gum-ball Coin-op

### ISSUE THREAD

**Issue by brian-lc** [ConsenSys/web3studio-projects#47]
## Concept
Make compute/storage/any simpleIO service as simple as a gumball machine. Coin goes in, gumball comes out. 
![gumball_dispenser.jpg](https://images.zenhubusercontent.com/5c1837597d7e6b6f82e3250e/7b7b6df2-173d-4792-a788-3fb2725a7e55)

## The Problem

Developers of simple web based services are forced to create large/difficult structures to charge for them. This project would serve by creating basic primitive to charge for usage. The concept is similar to ethereum gas but is a way to apply that same concept to any composable service. 

## How does it work?

1. Develop a service you would like to monitize
1. Add the coin-op shim/side-car process can track usage by account
1. Register service and define/document it's API and rate structure
1. Create OpenLaw contract for SLA, liability, security of service using boilerplate
1. Publish service and advertise it's features to other service developers (through a central app store like "API store")
1. Other developers/users can pull in API definitions into per-language/framework wrappers for easy RPC-like calls in their projects/services.
1. Other developers/users provide eth address to wallet, as they use published service, wallet balance is drawn down based on usage. 
1. Wallet empty? No more service provided.

## Existing Work

Unclear. This is essentially a new way of metering and charging for services ad-hoc. There must be others doing this or something similar. 
In theory this is better because it lowers the bar for monitizing a useful service in a way that doesn't require forming a business entity.

## Fit and Fitness

The idea is that this expands the potential users of ethereum. It goes after the long-tail side of webservices. The ideal service candidates are ones that are novel and useful but are not right for building a business around. With this system a developer can launch a service and charge for it right away. No need to provided services for free because setting up business entities to accept payments require a lot of work. The centralized registration service provides a channel for marketing and promoting the service similar to an app store.

## Assumptions

- OpenLaw can provide a contract that provides limits to liabilities similar to LLCs
- Service providers can effectively meeter their services. 
- Customers are okay with using services run/created by individuals and not businesses.
- The registration system is centralized and can provide some way of vetting API's/developers to prevent malicious behavior. 
- Side-cars/shim assume some kind of docker/k8 host so the services need to run on some cloud provider.
- Data processing can be encrypted end-to-end using customers public eth key.

**Comment by brian-lc** [comment]
Look into use of microchannel payments for settling up usage https://solidity.readthedocs.io/en/develop/solidity-by-example.html#micropayment-channel

**Comment by brian-lc** [comment]
Some kind of "app store" or index might be needed. Looking for more examples of something like this http://apis.io/ Following the sponsor links leads to some 404's. Not sure if/what is still active.

**Comment by barlock** [comment]
Twitter Survey: https://twitter.com/jwolpert/status/1114998520203939842

**Comment by brian-lc** [comment]
Someone building microservices following these principles would produce services that are good candidates for 'gumballizing' them...  https://medium.com/@jbgisbert/microservices-overview-30e505316a8

**Comment by brian-lc** [comment]
Turns out this idea is so good that other people have been working on it for quite a while 😸 
https://docs.iota.org/docs/getting-started/0.1/introduction/what-is-iota

**Comment by barlock** [comment]
👏
