### ISSUE TITLE
Create SideJam Repo

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-projects#53]
Readme should say, "Web3Studio doesn't just do open source projects. We do open source from the first line of code and the first fragment of an idea that leads to that code. SideJam is an approach to using the Ethereum mainnet as a message bus between confidential state machines. Get on board now. Raise your hand to be part of our first community call, and you'll be ahead of the pack as we figure out what this thing is going to be."

**Comment by barlock** [comment]
Issue moved to [ConsenSys/web3studio #52](https://github.com/ConsenSys/web3studio/issues/52) via [**ZenHub**](https://www.zenhub.com/)
